### ISSUE TITLE
Doesn't work with JS lambdas

### ISSUE THREAD

**Issue by angusdavisadobe** [jesperhh/qmlfmt#37] opened 2021-12-13 00:14 UTC
with this QML:
    onPressed: (mouse)=> {
          if (mouse.modifiers & Qt.AltModifier) {
             if (mouse.button == Qt.LeftButton) {
                 state = 1;
             } else if (mouse.button == Qt.RightButton) {
                 state = 2;
              } else if (mouse.button == Qt.MiddleButton) {
                   state = 3;
             }
          }
it produced:
     onPressed: function mouse }
        if (mouse.modifiers & Qt.AltModifier) {
            if (mouse.button == Qt.LeftButton) {
                state = 1
            } else if (mouse.button == Qt.RightButton) {
                state = 2
              } else if (mouse.button == Qt.MiddleButton) {
                  state = 3
              }
         }

**Comment by jesperhh** [comment] 2021-12-13 20:14
If you have a recent version of Qt Creator installed, can you check if the same issue reproduces if you reformat there?

**Comment by angusdavisadobe** [comment] 2021-12-14 03:38
I was using the command-line interface.  I don't have Qt Creator project so can't test there.

**Comment by jesperhh** [comment] 2021-12-14 20:23
Looks like this was mostly fixed in: https://bugreports.qt.io/browse/QTCREATORBUG-23019

Unfortunately, this case is still buggy, with Qt Cretor 6.0 it becomes:

```
import QtQuick 2.7

Item {
    MouseArea {
        onPressed: mouse =>
                   if (mouse.modifiers & Qt.AltModifier) {
                       if (mouse.button === Qt.LeftButton) {
                           state = 1
                       } else if (mouse.button === Qt.RightButton) {
                           state = 2
                       } else if (mouse.button === Qt.MiddleButton) {
                           state = 3
                       }
                   }
    }
}
}
```
You will need to report this bug against Qt Creator, as that is what this tool is built on.

**Closed** 2023-03-29 07:40 UTC
